name: Build PDF
run-name: Build PDF

on:
  push
permissions:
  contents: write

jobs:
  build-pdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install \
          pandoc \
          texlive-latex-base \
          texlive-latex-recommended \
          texlive-fonts-recommended 

    - name: Run pandoc
      run: |
         pandoc -s -o WhitePaper.pdf WhitePaper.md

    - name: Add to PDF to repo
      run: |
         git config user.name github-actions
         git config user.email github-actions@github.com
         git add WhitePaper.pdf
         git commit -m 'update pdf'
         git push origin ${{ github.ref }}
